version: "3.8"
services:
  web:
    build: ./app
    image: 891377031489.dkr.ecr.us-east-1.amazonaws.com/workshop2:workshop2_web # aws link
    command: gunicorn nc_tutorials.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
      - static_volume:/usr/src/app/static
    expose:
      - 8000
    environment:
      - DB_NAME=nc_tutorials_db # database name to be changed
      - DB_USER=postgres
      - DB_PASSWORD=admin123
      - DB_HOST=nctutorials.czo6maokyv8p.us-east-1.rds.amazonaws.com # aws link
      - DB_PORT=5432
      - DATABASE=postgres
      - VIRTUAL_HOST=ec2-52-87-132-174.compute-1.amazonaws.com # aws link
      - VIRTUAL_PORT=8000
  nginx:
    build: ./nginx
    image: 891377031489.dkr.ecr.us-east-1.amazonaws.com/workshop2:workshop2_nginx
    volumes:
      - static_volume:/usr/src/app/static
    ports:
      - 8000:80
    depends_on:
      - web
volumes:
  static_volume: